# Generated by Django 6.0.1 on 2026-03-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operatives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operative',
            name='nif',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='operative',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
