[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'cd backend && python manage.py migrate --noinput && cd .. && python gradio_app/app.py'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
