# Generated by Django 6.0.1 on 2026-01-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireparcel',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='fireparcel',
            name='vegetation_type',
        ),
        migrations.AddField(
            model_name='fireparcel',
            name='resp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fireparcel',
            name='resp_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
