# Generated by Django 6.0.1 on 2026-01-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_remove_fireparcel_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireparcel',
            name='infrastructure',
            field=models.CharField(choices=[('non_existing', 'Inexistente'), ('existing', 'Operacional'), ('req_maintenance', 'Manutenção necessária'), ('no_info', 'Sem informação')], default='no_info', max_length=50),
        ),
        migrations.AddField(
            model_name='fireparcel',
            name='owner_info',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='fireparcel',
            name='vegetation_type',
            field=models.CharField(choices=[('matos', 'Matos'), ('pinhal', 'Pinhal'), ('eucaliptal', 'Eucaliptal'), ('misto', 'Misto')], default='matos', max_length=20),
        ),
    ]
