# Generated by Django 6.0.1 on 2026-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_fireparcel_infrastructure_fireparcel_owner_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireparcel',
            name='concelho',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fireparcel',
            name='last_burned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
