# Generated by Django 6.0.1 on 2026-03-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0004_fireparcel_concelho_fireparcel_last_burned_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireparcel',
            name='area_ha',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
