# Generated by Django 6.0.1 on 2026-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operatives', '0001_initial'),
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operatives', models.ManyToManyField(related_name='fire_actions', to='operatives.operative')),
                ('parcels', models.ManyToManyField(related_name='fire_actions', to='parcels.fireparcel')),
            ],
        ),
    ]
