# Generated by Django 6.0.1 on 2026-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fireaction',
            name='execution_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
