# Generated by Django 6.0.1 on 2026-03-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_actions', '0002_fireaction_execution_date'),
        ('operatives', '0002_operative_nif_operative_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireaction',
            name='operatives',
        ),
        migrations.AddField(
            model_name='fireaction',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fireaction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fireaction',
            name='status',
            field=models.CharField(choices=[('Pre-Plano', 'Pré-Plano'), ('Executada', 'Executada')], default='Pre-Plano', max_length=20),
        ),
        migrations.CreateModel(
            name='BurningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('num_men', models.IntegerField(blank=True, null=True)),
                ('vehicles', models.TextField(blank=True, default='{}')),
                ('problems', models.TextField(blank=True, default='')),
                ('fuel_superficial', models.CharField(blank=True, default='', max_length=20)),
                ('fuel_manta_f', models.CharField(blank=True, default='', max_length=20)),
                ('fuel_manta_h', models.CharField(blank=True, default='', max_length=20)),
                ('weather_state', models.CharField(blank=True, default='', max_length=80)),
                ('wind_speed_beaufort', models.CharField(blank=True, default='', max_length=10)),
                ('wind_speed_kmh', models.CharField(blank=True, default='', max_length=20)),
                ('wind_direction', models.CharField(blank=True, default='', max_length=20)),
                ('fire_conduct', models.CharField(blank=True, choices=[('1', '1 - Contra o vento / contra o declive'), ('2', '2 - Por linhas sucessivas'), ('3', '3 - Perimetral'), ('4', '4 - De flanco'), ('5', '5 - Outro')], default='', max_length=2)),
                ('fire_conduct_other', models.TextField(blank=True, default='')),
                ('burn_effects', models.TextField(blank=True, default='')),
                ('burn_efficiency', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operatives', models.ManyToManyField(blank=True, related_name='burning_plans', to='operatives.operative')),
                ('pre_plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='burningplan', to='fire_actions.fireaction')),
            ],
        ),
    ]
